name: Webapp CI workflow

on:
  pull_request:
    branches: [main] # CI gets triggered on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE DATABASE users;"
          sudo -u postgres psql -c "CREATE USER ${{ secrets.DATABASE_USER }} WITH ENCRYPTED PASSWORD '${{ secrets.DATABASE_PASSWORD }}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE users TO ${{ secrets.DATABASE_USER }};"

      - name: Build with Maven
        run: mvn clean install -DskipTests # Compile the code and install dependencies without running tests

      - name: Run tests
        run: mvn test # Run your tests
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/users"
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DATABASE_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

#      - name: Build failure
#        run: exit 1
