name: Webapp CI workflow

on:
  pull_request:
    branches: [main] # CI gets triggered on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE DATABASE users;"
          sudo -u postgres psql -c "CREATE USER ${{ secrets.DATABASE_USER }} WITH ENCRYPTED PASSWORD '${{ secrets.DATABASE_PASSWORD }}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE users TO ${{ secrets.DATABASE_USER }};"

      - name: Create log directory
        run: |
          sudo mkdir -p /var/log/webapp
          sudo touch /var/log/webapp/webapp.log
          sudo chmod -R 777 /var/log/webapp
          sudo chmod 666 /var/log/webapp/webapp.log

      - name: Set up Google Cloud credentials
        run: echo -e "$GCLOUD_CREDENTIALS" > /tmp/credentials.json
        env:
          GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build with Maven
        run: mvn clean install -DskipTests # Compile the code and install dependencies without running tests

      - name: Run tests
        run: mvn test # Run your tests
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/users"
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DATABASE_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

#      - name: Build failure
#        run: exit 1
